<a href="https://colab.research.google.com/github/AnulipiJana/AI-Driven-Supply-Chain-Disruption-Predictor-and-Inventory-Optimization-System/blob/main/Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Setup**

In [ ]:
!pip install datasets evaluate transformers[sentencepiece]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 10.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 7.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 14.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.9/388.9 kB 12.9 MB/s eta 0:00:00
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.20.3
    Uninstalling huggingface-hub-0.20.3:
      Successfully uninstalled huggingface-hub-0.20.3


# Transformers, what can they do?

In [ ]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier ("He is dancing")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9995545744895935}]

In [ ]:
classifier = pipeline("sentiment-analysis")
classifier("I was very exited for this course . But it is okay")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9996625185012817}]

In [ ]:
from transformers import pipeline

classifier = pipeline("zero-shot-classification")
classifier(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business","health"]
    )

No model was supplied, defaulted to facebook/bart-large-mnli and revision c626438 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

{'sequence': 'This is a course about the Transformers library',
 'labels': ['education', 'business', 'health', 'politics'],
 'scores': [0.7774958610534668,
  0.1030777245759964,
  0.07944986969232559,
  0.039976585656404495]}

### **Text Generation**

In [ ]:
from transformers import pipeline
generator =  pipeline("text-generation")
generator("hey there! how are you ? i want to say")

No model was supplied, defaulted to openai-community/gpt2 and revision 6c0e608 (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'hey there! how are you ? i want to say hello to you too uhhh that has been a long, quiet evening. it must be some time before you all make it back home. its been a while.\n\n\ni just wanted to'}]

In [ ]:
from transformers import pipeline
#model name is mendatory
generator = pipeline("text-generation", model="distilgpt2")
generator(
    "hey there! how are you ? i want to say",
    #specify length and seq no are given by user
    max_length=50,
    num_return_sequences= 3,)

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'hey there! how are you ? i want to say hello ;-) ;-))'},
 {'generated_text': "hey there! how are you ? i want to say they're going to make a difference in your life, they'll give you life and their family. how can you keep them alive on their own and they will take you back to them? and"},
 {'generated_text': 'hey there! how are you ? i want to say this right now, i will show your guide there ive seen what i need to know about it ive seen what i need to know about it'}]

### **Fill Mask**

In [ ]:
from transformers import pipeline

unmasker = pipeline("fill-mask")
unmasker("I am a CSE student.I want to learn about <mask> model",top_k=2)

No model was supplied, defaulted to distilbert/distilroberta-base and revision ec58a5b (https://huggingface.co/distilbert/distilroberta-base).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Some weights of the model checkpoint at distilbert/distilroberta-base were not used when initializing RobertaForMaskedLM: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[{'score': 0.07595255970954895,
  'token': 265,
  'token_str': ' business',
  'sequence': 'I am a CSE student.I want to learn about business model'},
 {'score': 0.06897209584712982,
  'token': 127,
  'token_str': ' my',
  'sequence': 'I am a CSE student.I want to learn about my model'}]

In [ ]:
from transformers import pipeline

unmasker = pipeline("fill-mask", model="bert-base-uncased")
result = unmasker("This man works as a [MASK].")
print([r["token_str"] for r in result])

result = unmasker("This woman works as a [MASK].")
print([r["token_str"] for r in result])

result = unmasker("This person works as a [MASK].")
print([r["token_str"] for r in result])

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

['carpenter', 'lawyer', 'farmer', 'businessman', 'doctor']
['nurse', 'maid', 'teacher', 'waitress', 'prostitute']
['lawyer', 'teacher', 'nurse', 'contractor', 'manager']


### **name entity recognization**

In [ ]:
from transformers import pipeline

ner = pipeline("ner", grouped_entities=True)
ner("My name is Sylvain and I work at Hugging Face in Brooklyn.")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision f2482bf (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/token_classification.py:168: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="simple"` instead.
  warnings.warn(


[{'entity_group': 'PER',
  'score': 0.9981694,
  'word': 'Sylvain',
  'start': 11,
  'end': 18},
 {'entity_group': 'ORG',
  'score': 0.9796019,
  'word': 'Hugging Face',
  'start': 33,
  'end': 45},
 {'entity_group': 'LOC',
  'score': 0.9932106,
  'word': 'Brooklyn',
  'start': 49,
  'end': 57}]

### **Question-answering**

In [ ]:
from transformers import pipeline

question_answerer = pipeline("question-answering")
question_answerer(
    question="Where do I study?",
    context="My name is Sylvain and I study in Kiit",
)

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

{'score': 0.9783604741096497, 'start': 34, 'end': 38, 'answer': 'Kiit'}

In [ ]:
question_answerer = pipeline("question-answering")
question_answerer(
    question="do you like this ?",
    context = "This is only the first lesson. May be it will be interesting later."
)

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'score': 0.10301292687654495,
 'start': 31,
 'end': 66,
 'answer': 'May be it will be interesting later'}

### **Summarization**

In [ ]:
from transformers import pipeline

summarizer = pipeline("summarization")

summarizer("Nano-medicine can improve treatment methods. Toxicity of treatments can be improved using nanotechnology. This paper discusses the medical effects of various types of nanoparticles and a study on how it can be collaborated with predictive analytics and artificial intelligence for improvised healthcare methods.",max_length=20)

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/1.80k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

Your min_length=56 must be inferior than your max_length=20.
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1165: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (20). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length.
  warnings.warn(


[{'summary_text': ' Nano-medicine can be collaborated with predictive analytics and artificial intelligence for improvised healthcare'}]

### **Translation**

In [ ]:
from transformers import pipeline

translator = pipeline("translation", model="Helsinki-NLP/opus-mt-fr-en")
translator("Ce cours est produit par Hugging Face.")

config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/301M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/778k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.34M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")


[{'translation_text': 'This course is produced by Hugging Face.'}]

In [ ]:
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-en-fr")
translator("This course is produced by Hugging Face.")

config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/301M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/778k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.34M [00:00<?, ?B/s]

[{'translation_text': 'Ce cours est produit par Hugging Face.'}]

# Using Transformer

create a account

In [ ]:
! pip install huggingface_hub

!huggingface-cli login
#Log in using a token from huggingface.co/settings/tokens
#Create a model or dataset repo from the CLI if needed
#huggingface-cli repo create repo_name --type {model, dataset, space}

ERROR: Operation cancelled by user

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To login, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible): Traceback (most recent call last):
  File "/usr/local/bin/huggingface-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/commands/huggingface_cli.py", line 49, in main
  File "/usr/

## Behind the pipeline
- TOKENIZATION --> raw text to input IDs
- MODEL --> input IDs to logits
- POST-PROCESSING --> logits to prediction

In [ ]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier(
    [
        "I've been waiting for a HuggingFace course my whole life.",
        "I hate this so much!",
    ]
)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9598048329353333},
 {'label': 'NEGATIVE', 'score': 0.9994558691978455}]

## *PYTORCH*
### Raw text to Tokens
- Input ID
- Tokens

In [ ]:
from transformers import AutoTokenizer

#used to refer to a specific fine-tuned version of the DistilBERT model for sentiment analysis on the Stanford Sentiment Treebank (SST-2) dataset in English.
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint) #method

In [ ]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt") #To specify the type of tensors-return_tensors , To set the length-paddding

print("...PT INPUTS ...\n")
print(inputs)
print("\n... TOKENIZER ...\n")
print(tokenizer)
print("\n... RAW INPUTS ...")
print(raw_inputs)

...PT INPUTS ...

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

... TOKENIZER ...

DistilBertTokenizerFast(name_or_path='distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=

### Input Ids to Logits
- output shape
- Automodel
- AutoModelForSequenceClassification

In [ ]:
from transformers import AutoModel

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModel.from_pretrained(checkpoint)
outputs = model(**inputs)
print("TF OUTPUT SHAPE ...\n")
print(outputs.last_hidden_state.shape)
#Tensor has 2 sentences each has 16 tokens and hidden size of the model is 768

TF OUTPUT SHAPE ...

torch.Size([2, 16, 768])


- for classification problem

In [ ]:
from transformers import AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**inputs)

print("TF OUTPUT SHAPE ...\n")
print(outputs.logits.shape)

TF OUTPUT SHAPE ...

torch.Size([2, 2])


In [ ]:
#Logits , the raw, unnormalized scores outputted by the last layer of the model . Sum of these vlues is not 1
print(outputs.logits)

tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)


### Logits to Prediction
- Use SOFTMAX to get the probability from logits
- To get the labels corresponding to each position

In [ ]:
import torch

predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)# Calculate the softmax of the output logits

print("PT OUTPUT PROBABILITIES ...\n")
print(predictions)

print("\n\n... PT OUTPUT PROBABILITIES WITH LABEL TITLES ...\n")
for i, pred in enumerate(predictions): print(f"Sentence #{i+1} - Classification Probabilities:\n\t{model.config.id2label[0]}: %{100*pred[0]:.3f}\n\t{model.config.id2label[1]}: %{100*pred[1]:.3f}")

print("\n\n... MODEL LABEL ...\n")
print(model.config.id2label)

PT OUTPUT PROBABILITIES ...

tensor([[4.0195e-02, 9.5980e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)


... PT OUTPUT PROBABILITIES WITH LABEL TITLES ...

Sentence #1 - Classification Probabilities:
	NEGATIVE: %4.020
	POSITIVE: %95.980
Sentence #2 - Classification Probabilities:
	NEGATIVE: %99.946
	POSITIVE: %0.054


... MODEL LABEL ...

{0: 'NEGATIVE', 1: 'POSITIVE'}


## *TENSERFLOW*
### Raw text to Tokens
- Input ID
- Tokens

In [ ]:
from transformers import AutoTokenizer

#used to refer to a specific fine-tuned version of the DistilBERT model for sentiment analysis on the Stanford Sentiment Treebank (SST-2) dataset in English.
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint) #method

In [ ]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",]
tf_inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="tf") #To specify the type of tensors use return_tensors

print("... PT INPUTS ...")
print(tf_inputs)
print("\n... TOKENIZER ...")
print(tokenizer)
print("\n... RAW INPUTS ...")
print(raw_inputs)

... PT INPUTS ...
{'input_ids': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662,
        12172,  2607,  2026,  2878,  2166,  1012,   102],
       [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,
            0,     0,     0,     0,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 16), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>}

... TOKENIZER ...
DistilBertTokenizerFast(name_or_path='distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, sin

### Input Ids to Logits
- output shape
 - Automodel
 - AutoModelForSequenceClassification

In [ ]:
from transformers import TFAutoModel

# Load the tensorflow version of the model from the checkpoint
tf_model = TFAutoModel.from_pretrained(checkpoint)

tf_outputs = tf_model(tf_inputs)

print("\n... TF OUTPUT SHAPE ...")
print(tf_outputs.last_hidden_state.shape)
print("\n\n... TF RAW OUTPUTS ...\n")
print(tf_outputs)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight', 'classifier.bias']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.



... TF OUTPUT SHAPE ...
(2, 16, 768)


... TF RAW OUTPUTS ...

TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(2, 16, 768), dtype=float32, numpy=
array([[[-0.17977984,  0.23332864,  0.6320985 , ..., -0.30166635,
          0.50081986,  0.14814362],
        [ 0.2757769 ,  0.64971244,  0.3199769 , ..., -0.07599559,
          0.5136171 ,  0.13292244],
        [ 0.9045854 ,  0.09851371,  0.2949724 , ...,  0.3351949 ,
         -0.14074141, -0.6464028 ],
        ...,
        [ 0.14658947,  0.56606007,  0.32352793, ..., -0.33757478,
          0.5099775 , -0.05610842],
        [ 0.75000423,  0.04872622,  0.1738002 , ...,  0.46841496,
          0.00296654, -0.60837543],
        [ 0.05194443,  0.37294856,  0.52233255, ...,  0.35840544,
          0.65004265, -0.38829824]],

       [[-0.29370666,  0.7282561 , -0.14972687, ..., -0.11868069,
         -1.0226727 , -0.04215699],
        [-0.22063622,  0.938384  , -0.095125  , ..., -0.3643167 ,
         -0.66052216,  0.24069703],
        [-0.153

In [ ]:
from transformers import TFAutoModelForSequenceClassification

# Load the tensorflow model for sequence classification
tf_model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

tf_outputs = tf_model(tf_inputs) # `Call` the model

print("\n... TF OUTPUT LOGITS' SHAPE ...")
print(tf_outputs.logits.shape)
print("\n\n... TF RAW OUTPUTS ...\n")
print(tf_outputs)

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.



... TF OUTPUT LOGITS' SHAPE ...
(2, 2)


... TF RAW OUTPUTS ...

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.5606961,  1.6122813],
       [ 4.1692314, -3.3464477]], dtype=float32)>, hidden_states=None, attentions=None)


### Logits to Prediction
- Use SOFTMAX to get the probability from logits
- To get the labels corresponding to each position

In [ ]:
print(tf_outputs.logits)

tf.Tensor(
[[-1.5606961  1.6122813]
 [ 4.1692314 -3.3464477]], shape=(2, 2), dtype=float32)


In [ ]:
import tensorflow as tf

# Calculate the softmax of the output logits
tf_predictions = tf.math.softmax(tf_outputs.logits, axis=-1)

print("... MODEL LABEL MAP ...")
print(tf_model.config.id2label)
print("\n\n... TF OUTPUT PROBABILITIES ...")
print(tf_predictions)
print("\n\n... TF OUTPUT PROBABILITIES WITH LABEL TITLES ...\n")
for i, pred in enumerate(tf_predictions): print(f"Sentence #{i+1} - Classification Probabilities:\n\t{tf_model.config.id2label[0]}: %{100*pred[0]:.3f}\n\t{tf_model.config.id2label[1]}: %{100*pred[1]:.3f}\n")

... MODEL LABEL MAP ...
{0: 'NEGATIVE', 1: 'POSITIVE'}


... TF OUTPUT PROBABILITIES ...
tf.Tensor(
[[4.0195391e-02 9.5980465e-01]
 [9.9945587e-01 5.4418371e-04]], shape=(2, 2), dtype=float32)


... TF OUTPUT PROBABILITIES WITH LABEL TITLES ...

Sentence #1 - Classification Probabilities:
	NEGATIVE: %4.020
	POSITIVE: %95.980

Sentence #2 - Classification Probabilities:
	NEGATIVE: %99.946
	POSITIVE: %0.054



## Creating a Transformer

In [ ]:
from transformers import AutoModel

bert_model = AutoModel.from_pretrained('bert-base-cased')
gpt_model = AutoModel.from_pretrained('gpt2')

print (type(gpt_model))
print (type(bert_model))

<class 'transformers.models.gpt2.modeling_gpt2.GPT2Model'>
<class 'transformers.models.bert.modeling_bert.BertModel'>


In [ ]:
from transformers import AutoConfig

bert_config = AutoConfig.from_pretrained('bert-base-cased')
gpt_config = AutoConfig.from_pretrained('gpt2')

print (type(gpt_config))
print (type(bert_config))

<class 'transformers.models.gpt2.configuration_gpt2.GPT2Config'>
<class 'transformers.models.bert.configuration_bert.BertConfig'>


In [ ]:
from transformers import BertConfig, BertModel

# Building the config
config = BertConfig()

# Building the model from the config
model = BertModel(config)
print("BERT CONFIG ...\n")
print(config)

BERT CONFIG ...

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.40.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



### Loading a Transformer model that is already trained

In [ ]:
from transformers import BertModel

model = BertModel.from_pretrained("bert-base-cased")

### Save model

In [ ]:
model.save_pretrained("C:/Users/Anulipi Jana/Documents/Project Work/Hugging Face/Transformer")

## Using a Transformer model for inference

In [ ]:
# Define the initial sequences (raw)
sequences = ["Hello!", "Cool.", "Nice!"]
print(f"SEQUENCES --> {sequences}")
for seq in sequences: print(f"\t--> {seq}")

# Tokenize the sequences (encoded)
encoded_sequences = tokenizer(sequences)["input_ids"]
print(f"\n ENCODED SEQUENCES --> {encoded_sequences}")
for enc_seq in encoded_sequences: print(f"\t--> {enc_seq}")

SEQUENCES --> ['Hello!', 'Cool.', 'Nice!']
	--> Hello!
	--> Cool.
	--> Nice!

 ENCODED SEQUENCES --> [[101, 7592, 999, 102], [101, 4658, 1012, 102], [101, 3835, 999, 102]]
	--> [101, 7592, 999, 102]
	--> [101, 4658, 1012, 102]
	--> [101, 3835, 999, 102]


### Tensorflow



In [ ]:
tf_model_inputs = tf.constant(encoded_sequences)
print("TENSORFLOW MODEL INPUTS - TENSORS\n")
print(tf_model_inputs)

TENSORFLOW MODEL INPUTS - TENSORS

tf.Tensor(
[[ 101 7592  999  102]
 [ 101 4658 1012  102]
 [ 101 3835  999  102]], shape=(3, 4), dtype=int32)


## Using the tensors as inputs to the model

In [ ]:
tf_output = tf_model(tf_model_inputs)
print("TENSORFLOW MODEL OUTPUTS ...\n")
print(tf_output)

TENSORFLOW MODEL OUTPUTS ...

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-3.7234986,  3.9690616],
       [-4.2218633,  4.580667 ],
       [-4.285249 ,  4.6165524]], dtype=float32)>, hidden_states=None, attentions=None)


### Pytorch

In [ ]:
import torch
pt_model_inputs = torch.tensor(encoded_sequences)
print("... PYTORCH MODEL INPUTS - TENSORS\n")
print(pt_model_inputs)

... PYTORCH MODEL INPUTS - TENSORS

tensor([[ 101, 7592,  999,  102],
        [ 101, 4658, 1012,  102],
        [ 101, 3835,  999,  102]])


In [ ]:
pt_output = model(pt_model_inputs)
print("PYTORCH MODEL OUTPUTS ...\n")
print(pt_output)

PYTORCH MODEL OUTPUTS ...

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 4.4496e-01,  4.8276e-01,  2.7797e-01,  ..., -5.4032e-02,
           3.9393e-01, -9.4770e-02],
         [ 2.4943e-01, -4.4093e-01,  8.1772e-01,  ..., -3.1917e-01,
           2.2992e-01, -4.1172e-02],
         [ 1.3668e-01,  2.2518e-01,  1.4502e-01,  ..., -4.6915e-02,
           2.8224e-01,  7.5566e-02],
         [ 1.1789e+00,  1.6738e-01, -1.8187e-01,  ...,  2.4671e-01,
           1.0441e+00, -6.1974e-03]],

        [[ 3.6436e-01,  3.2464e-02,  2.0258e-01,  ...,  6.0110e-02,
           3.2451e-01, -2.0996e-02],
         [ 7.1866e-01, -4.8725e-01,  5.1740e-01,  ..., -4.4012e-01,
           1.4553e-01, -3.7545e-02],
         [ 3.3223e-01, -2.3271e-01,  9.4876e-02,  ..., -2.5268e-01,
           3.2172e-01,  8.1076e-04],
         [ 1.2523e+00,  3.5754e-01, -5.1321e-02,  ..., -3.7840e-01,
           1.0526e+00, -5.6255e-01]],

        [[ 2.4042e-01,  1.4718e-01,  1.2110e-01,  ...,  7.6062e-02

# Tokenization

In [ ]:
from transformers import AutoTokenizer

#used to refer to a specific fine-tuned version of the DistilBERT model for sentiment analysis on the Stanford Sentiment Treebank (SST-2) dataset in English.
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint) #method

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [ ]:
# Define sentences to test on
text_1 = "Jim Henson was a puppeteer"
text_2 = "Let's do tokenization!"
print(f"ORIGINAL \n'{text_1}'\n'{text_2}'")

wb_tokens_1 = text_1.split()
wb_tokens_2 = text_2.split()
print(f"\nWORD-BASED TOKENS\n{wb_tokens_1}\n{wb_tokens_2}")

cb_tokens_1 = [x for x in text_1 if x != " "]
cb_tokens_2 = [x for x in text_2 if x != " "]
print(f"\nCHARACTER-BASED TOKENS\n{cb_tokens_1}\n{cb_tokens_2}")

sw_tokens_1 = tokenizer.tokenize(text_1)
sw_tokens_2 = tokenizer.tokenize(text_2)
print(f"\nSUBWORD-BASED TOKENS\n{sw_tokens_1}\n{sw_tokens_2}")

ORIGINAL 
'Jim Henson was a puppeteer'
'Let's do tokenization!'

WORD-BASED TOKENS
['Jim', 'Henson', 'was', 'a', 'puppeteer']
["Let's", 'do', 'tokenization!']

CHARACTER-BASED TOKENS
['J', 'i', 'm', 'H', 'e', 'n', 's', 'o', 'n', 'w', 'a', 's', 'a', 'p', 'u', 'p', 'p', 'e', 't', 'e', 'e', 'r']
['L', 'e', 't', "'", 's', 'd', 'o', 't', 'o', 'k', 'e', 'n', 'i', 'z', 'a', 't', 'i', 'o', 'n', '!']

SUBWORD-BASED TOKENS
['jim', 'henson', 'was', 'a', 'puppet', '##eer']
['let', "'", 's', 'do', 'token', '##ization', '!']


## Loading
### BertTokenizer

In [ ]:
from transformers import BertTokenizer

tokenizer1 = BertTokenizer.from_pretrained("bert-base-cased")

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [ ]:
tokenizer1("Using a Transformer network is simple")

{'input_ids': [101, 7993, 170, 13809, 23763, 2443, 1110, 3014, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}

### AutoTokenizer

In [ ]:
from transformers import AutoTokenizer

tokenizer2 = AutoTokenizer.from_pretrained("bert-base-cased")

In [ ]:
tokenizer2("Using a Transformer network is simple")

{'input_ids': [101, 7993, 170, 13809, 23763, 2443, 1110, 3014, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}

## Saving

In [ ]:
tokenizer1.save_pretrained("C:/Users/Anulipi Jana/Documents/Project Work/Hugging Face/Transformer")

('C:/Users/Anulipi Jana/Documents/Project Work/Hugging Face/Transformer/tokenizer_config.json',
 'C:/Users/Anulipi Jana/Documents/Project Work/Hugging Face/Transformer/special_tokens_map.json',
 'C:/Users/Anulipi Jana/Documents/Project Work/Hugging Face/Transformer/vocab.txt',
 'C:/Users/Anulipi Jana/Documents/Project Work/Hugging Face/Transformer/added_tokens.json')

## Tokenizer Pipeline
### Encoding

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

sequence = "Using a Transformer network is simple"
tokens = tokenizer.tokenize(sequence)

print(tokens)
# "##" indicate that token not a begining of a word.

['Using', 'a', 'Trans', '##former', 'network', 'is', 'simple']


In [ ]:
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

[7993, 170, 13809, 23763, 2443, 1110, 3014]


### Decoding

In [ ]:
decoded_string = tokenizer.decode([7993, 170, 11303, 1200, 2443, 1110, 3014])
print(decoded_string)

Using a transformer network is simple


In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
sen = "let's try to tokenize"
token = tokenizer.tokenize(sen)
print (token)
ip_ids = tokenizer.convert_tokens_to_ids(token)
print(ip_ids)

final_inputs = tokenizer.prepare_for_model(ip_ids)
print(final_inputs("ip_ids"))

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


['let', "'", 's', 'try', 'to', 'token', '##ize']
[2292, 1005, 1055, 3046, 2000, 19204, 4697]


TypeError: 'BatchEncoding' object is not callable

# Multiple sentence

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
print ("tokens: \n",tokens)
ids = tokenizer.convert_tokens_to_ids(tokens)
print ("\nIDs: \n",ids)

input_ids = torch.tensor(ids)
# This line will fail.
model(input_ids)

tokens: 
 ['i', "'", 've', 'been', 'waiting', 'for', 'a', 'hugging', '##face', 'course', 'my', 'whole', 'life', '.']

IDs: 
 [1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012]


IndexError: too many indices for tensor of dimension 1

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
print ("tokens: \n",tokens)

ids = tokenizer.convert_tokens_to_ids(tokens)
print ("\nIDs: \n",ids)

input_ids = torch.tensor([ids])
print("\nInput IDs:\n", input_ids)

output = model(input_ids)
print("\nLogits:\n", output.logits)

print("\nLogits Shape:\n", output.logits.shape)

tokens: 
 ['i', "'", 've', 'been', 'waiting', 'for', 'a', 'hugging', '##face', 'course', 'my', 'whole', 'life', '.']

IDs: 
 [1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012]

Input IDs:
 tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1012]])

Logits:
 tensor([[-2.7276,  2.8789]], grad_fn=<AddmmBackward0>)

Logits Shape:
 torch.Size([1, 2])


## Padding

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence1_ids = [[200, 200, 200]]
sequence2_ids = [[200, 200]]
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

print(model(torch.tensor(sequence1_ids)).logits)
print(model(torch.tensor(sequence2_ids)).logits)
print(model(torch.tensor(batched_ids)).logits)

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.


tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
tensor([[ 1.5694, -1.3895],
        [ 1.3374, -1.2163]], grad_fn=<AddmmBackward0>)


## Attension mask
To get the same result when passing individual sentences of different lengths

In [ ]:
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

attention_mask = [
    [1, 1, 1],
    [1, 1, 0],
]

outputs = model(torch.tensor(batched_ids), attention_mask=torch.tensor(attention_mask))
print(outputs.logits)

tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)


# Putting it all together

In [ ]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

sequence = "I've been waiting for a HuggingFace course my whole life."
sequences_same_length = ["Been holding out for a HuggingFace course my entire life.", "I've waited for a HuggingFace course so long!"]
sequences_diff_length = ["I've been waiting for a HuggingFace course my whole life.", "So have I!"]

print("... WHAT CAN THE TOKENIZER OBJECT DO? ...\n")
print ("TOKENIZE A SINGLE SEQUENCE")
print("(RETURN TF COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequence, return_tensors='tf')}")
print("(RETURN PT COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequence, return_tensors='pt')}")

print("\n\nTOKENIZE MULTIPLE SEQUENCES - SAME LENGTH")
print("(RETURN TF COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_same_length, return_tensors='tf')}")
print("(RETURN PT COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_same_length, return_tensors='pt')}")

print("\n\nTOKENIZE MULTIPLE SEQUENCES - DIFFERENT LENGTH")
print("(RETURN TF COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='tf', padding=True)}")
print("(RETURN PT COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='pt', padding=True)}")

print("\n\nPADDING UP TO SEQUENCE MAX LENGTH") # Will pad the sequences up to the maximum sequence length
print("(RETURN TF COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='tf', padding='longest')}")
print("(RETURN PT COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='pt', padding='longest')}")

print("\n\nPADDING UP TO MODEL MAX LENGTH")
# Will pad the sequences up to the model max length (512 for BERT or DistilBERT)
print("(RETURN TF COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='tf', padding='max_length')}")
print("(RETURN PT COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='pt', padding='max_length')}")

print("\n\nPADDING UP TO SPECIFIED LENGTH")# Will pad the sequences up to the specified max length
print("(RETURN TF COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='tf', padding='max_length', max_length=8, truncation=True)}")
print("(RETURN PT COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='pt', padding='max_length', max_length=8, truncation=True)}")

print("\n\nTRUNCATE TO MODEL MAX LENGTH")
# Will truncate the sequences that are longer than the model max length(512 for BERT or DistilBERT)
print("(RETURN TF COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='tf', truncation=True, padding=True)}")
print("(RETURN PT COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='pt', truncation=True, padding=True)}")

print("\n\nTRUNCATE TO A SPECIFIED LENGTH")# Will truncate the sequences that are longer than the specified max length
print("(RETURN TF COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='tf', padding=True, truncation=True, max_length=8)}")
print("(RETURN PT COMPATIBLE TENSORS)")
print(f"\t--> {tokenizer(sequences_diff_length, return_tensors='pt', padding=True, truncation=True, max_length=8)}")

... WHAT CAN THE TOKENIZER OBJECT DO? ...

TOKENIZE A SINGLE SEQUENCE
(RETURN TF COMPATIBLE TENSORS)
	--> {'input_ids': <tf.Tensor: shape=(1, 16), dtype=int32, numpy=
array([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662,
        12172,  2607,  2026,  2878,  2166,  1012,   102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 16), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}
(RETURN PT COMPATIBLE TENSORS)
	--> {'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


TOKENIZE MULTIPLE SEQUENCES - SAME LENGTH
(RETURN TF COMPATIBLE TENSORS)
	--> {'input_ids': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[  101,  2042,  3173,  2041,  2005,  1037, 17662, 12172,  2607,
         2026,  2972,  2166,  1012,   102],
       [  101,  1045,  1005,  2310

## SPECIAL TOKENS

In [ ]:
sequence = "I've been waiting for a HuggingFace course my whole life."
print("SEQUENCE:")
print(f"\t--> '{sequence}'")

model_inputs = tokenizer(sequence)
print("MODEL INPUT IDS (STYLE 1 - FOR MODEL CONSUMPTION)")
print("\t-->", model_inputs["input_ids"])

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
print("MODEL INPUT IDS (STYLE 2 - DIRECT CONVERSION NOT READY FOR MODEL)")
print("\t-->", ids)

decoded_style_1 = tokenizer.decode(model_inputs["input_ids"])
print("MODEL INPUT IDS DECODED (STYLE 1 - FOR MODEL CONSUMPTION)")
print(f"\t--> '{decoded_style_1}'")

decoded_style_2 = tokenizer.decode(ids)
print("MODEL INPUT IDS DECODED (STYLE 2 - DIRECT CONVERSION NOT READY FOR MODEL)")
print(f"\t--> '{decoded_style_2}'")

SEQUENCE:
	--> 'I've been waiting for a HuggingFace course my whole life.'
MODEL INPUT IDS (STYLE 1 - FOR MODEL CONSUMPTION)
	--> [101, 1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012, 102]
MODEL INPUT IDS (STYLE 2 - DIRECT CONVERSION NOT READY FOR MODEL)
	--> [1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1012]
MODEL INPUT IDS DECODED (STYLE 1 - FOR MODEL CONSUMPTION)
	--> '[CLS] i've been waiting for a huggingface course my whole life. [SEP]'
MODEL INPUT IDS DECODED (STYLE 2 - DIRECT CONVERSION NOT READY FOR MODEL)
	--> 'i've been waiting for a huggingface course my whole life.'


# WRAPPING UP: FROM TOKENIZER TO MODEL

## Pytorch

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
sequences = ["I've been waiting for a HuggingFace course my whole life.", "So have I!"]

tokens = tokenizer(sequences, padding=True, truncation=True, return_tensors="pt")
output = model(**tokens)
print(f"PYTORCH MODEL OUTPUT\n\n{output}")

PYTORCH MODEL OUTPUT

SequenceClassifierOutput(loss=None, logits=tensor([[-1.5607,  1.6123],
        [-3.6183,  3.9137]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


## Tensorflow

In [ ]:
# Step 1 - Imports
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

# Step 2 - Initialize Tokenizer and Model
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
# Step 3 - Create a list of sentences
sequences = ["I've been waiting for a HuggingFace course my whole life.", "So have I!"]

# Step 4 - Tokenize the sentences and pass them to the model
tokens = tokenizer(sequences, padding=True, truncation=True, return_tensors="tf")
output = model(**tokens)

# Step 5 - Print the output
print(f"TENSORFLOW MODEL OUTPUT\n\n{output}")

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


TENSORFLOW MODEL OUTPUT

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.5606961,  1.6122813],
       [-3.618318 ,  3.9137495]], dtype=float32)>, hidden_states=None, attentions=None)


# Finu Tuning

In [ ]:
!pip install datasets evaluate transformers[sentencepiece]

In [ ]:
import numpy as np
import torch
from transformers import AdamW, AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained (checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
sequences = [
    "I've been waiting for a HuggingFace course my whole life.",
    "This course is amazing!",
]
batch = tokenizer(sequences, padding=True, truncation=True, return_tensors="pt")

# This is new
batch["labels"] = torch.tensor([1, 1])

optimizer = AdamW(model.parameters())
loss = model(**batch).loss
loss.backward()
optimizer.step()

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:521: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [ ]:
from datasets import load_dataset

# Download and cache the dataset
raw_datasets = load_dataset("glue", "mrpc")

# Print the DatasetDict Object
print("RAW DATASET OBJECT - GLUE/MRPC\n")
print(raw_datasets)

# Access the train subset of the dataset (Dataset Object)
raw_train_dataset = raw_datasets["train"]
print("\nTRAIN DATASET\n")
print(raw_train_dataset)

# Access an example from the train subset of the dataset (Dict)
raw_train_ex = raw_train_dataset[0]
print("\nTRAIN EXAMPLE - IDX=0\n")
for k,v in raw_train_ex.items(): print(f"\t--> {k:<10}: {v}")

# Access features of our Dataset Object (Dict)
raw_train_features = raw_train_dataset.features
print("\nTRAIN DATASET FEATURES\n")
for k,v in raw_train_features.items(): print(f"\t--> {k:<10}: {v}")

# Access the indices from the train and val subsets of the dataset
print("\nLABEL - TRAIN SUBSET - IDX=15\n")
for k,v in raw_datasets["train"][15].items():
    print(f"\t--> **{k}** : {v} ({raw_train_dataset.features['label'].names[v]})") if k=="label" else print(f"\t--> {k:<10}: {v}")

print("LABEL - VAL SUBSET - IDX=87\n")
for k,v in raw_datasets["validation"][87].items():
    print(f"\t--> **{k}** : {v} ({raw_train_dataset.features['label'].names[v]})") if k=="label" else print(f"\t--> {k:<10}: {v}")

# For spacing
print("\n")

Generating train split:   0%|          | 0/3668 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/408 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1725 [00:00<?, ? examples/s]

RAW DATASET OBJECT - GLUE/MRPC

DatasetDict({
    train: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 408
    })
    test: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 1725
    })
})

TRAIN DATASET

Dataset({
    features: ['sentence1', 'sentence2', 'label', 'idx'],
    num_rows: 3668
})

TRAIN EXAMPLE - IDX=0

	--> sentence1 : Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .
	--> sentence2 : Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .
	--> label     : 1
	--> idx       : 0

TRAIN DATASET FEATURES

	--> sentence1 : Value(dtype='string', id=None)
	--> sentence2 : Value(dtype='string', id=None)
	--> label     : ClassLabel(names=['not_equivalent', 'equivalent'], id

## Preprocessing Sentence Pairs

In [ ]:
from transformers import AutoTokenizer

checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
tokenized_sentences_1 = tokenizer(raw_datasets["train"]["sentence1"])
tokenized_sentences_2 = tokenizer(raw_datasets["train"]["sentence2"])

print("FIRST 3 ORIGINAL SENTENCE PAIRS")
for i in range(3): print(f"\tSENTENCE 1 --> '{raw_datasets['train']['sentence1'][i]}'\n\tSENTENCE 2 --> '{raw_datasets['train']['sentence2'][i]}'\n")

print("\nFIRST 3 TOKENIZED SENTENCE PAIRS")
for i in range(3): print(f"\tSENTENCE 1 --> '{tokenized_sentences_1[i]}'\n\tSENTENCE 2 --> '{tokenized_sentences_2[i]}'\n")

e15_s1 = raw_datasets['train']['sentence1'][15]
e15_s2 = raw_datasets['train']['sentence2'][15]

print("\nELEMENT 15 - ORIGINAL SENTENCE PAIRS")
print(f"\tSENTENCE 1 --> '{e15_s1}'\n\tSENTENCE 2 --> '{e15_s2}'\n")

e15_tokenize_seperately_s1 = tokenizer.convert_ids_to_tokens(tokenizer(e15_s1)["input_ids"])
e15_tokenize_seperately_s2 = tokenizer.convert_ids_to_tokens(tokenizer(e15_s2)["input_ids"])
e15_tokenized_together = tokenizer(e15_s1, e15_s2)
e15_tokens = tokenizer.convert_ids_to_tokens(e15_tokenized_together["input_ids"])

print("\nELEMENT 15 - TOKENIZED SEPERATELY")
print(f"\tSENTENCE 1 --> {' '.join(e15_tokenize_seperately_s1)}\n\tSENTENCE 2 --> {' '.join(e15_tokenize_seperately_s2)}\n")

print("\nELEMENT 15 - TOKENIZED TOGETHER")
print(f"\tSENTENCES --> {' '.join(e15_tokens)}\n")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


FIRST 3 ORIGINAL SENTENCE PAIRS
	SENTENCE 1 --> 'Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .'
	SENTENCE 2 --> 'Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .'

	SENTENCE 1 --> 'Yucaipa owned Dominick 's before selling the chain to Safeway in 1998 for $ 2.5 billion .'
	SENTENCE 2 --> 'Yucaipa bought Dominick 's in 1995 for $ 693 million and sold it to Safeway for $ 1.8 billion in 1998 .'

	SENTENCE 1 --> 'They had published an advertisement on the Internet on June 10 , offering the cargo for sale , he added .'
	SENTENCE 2 --> 'On June 10 , the ship 's owners had published an advertisement on the Internet , offering the explosives for sale .'


FIRST 3 TOKENIZED SENTENCE PAIRS
	SENTENCE 1 --> 'Encoding(num_tokens=25, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])'
	SENTENCE 2 --> 'Encoding(num_tokens=26, attributes=[i